deploy:
    stage: deploy
    environment:
        name: development
        url: http://188.166.214.118:9090
    tags:
        - s1
    before_script:
        - echo "create Dir backup java"
        - |
          if [ -d /backup/agregate_service ]; then 
            echo "Directory Is exists."; 
          else 
            mkdir -p /backup/agregate_service;
            echo "Create Directory backup Success...";
          fi
        - echo "create Dir App java"
        - |
          if [ -d /app ]; then 
            echo "Directory Is exists."; 
          else 
            mkdir -p /app;
            echo "Create Directory Success...";
          fi
        
    script: 
        - cd $DIR_RELEASE/agregate_service && pwd
        - echo "Extract Package...."
        - |
          if unzip *.zip 2>/dev/null; then
            echo 'All is good, archive extracted' >&2;
          else
            echo 'Archive failed to extract' >&2;
            rm -rf $DIR_RELEASE/agregate_service/*;
            cd $CI_BUILDS_DIR && pwd;
            zip -r artifacts.zip build/libs && mv artifacts.zip $DIR_RELEASE/agregate_service/;
            unzip -B $DIR_RELEASE/agregate_service/artifacts.zip;
          echo "Archiving Package success...!";
          fi       
        - echo "Checking Status Service..."  
        - |
          if [ $(jps -l | grep $SERVICE_NAME | wc -l) -eq "0" ]; then
            echo "service not running";
          else
            echo "service is running";  
            echo "killing Service $SERVICE_NAME";
            kill $(ps aux | grep $SERVICE_NAME | grep -v 'grep' | awk '{print $2}');
            echo "kill service success";
          fi        
        - echo "Preparing remove packages java..."        
        - mv $DIR_RELEASE/agregate_service/build/libs/* /app 
        - pwd        
        - echo "Make Sure Privileges user.."
        - ls -ltr /app
        - chown -R appuser01:appuser01 /app && chmod -R 755 /app
        - echo "Preparing start service java..."
        - su appuser01 && cd /app 
        - |
          if [ -f "builds-0.0.1-SNAPSHOT.jar" ]; then
            echo "File jar Found in here...";
            ln -sv /app/builds-0.0.1-SNAPSHOT.jar  /app/builds.jar;
          else
            echo "FIle is Not Found in here...!";           
          fi
        
        - java -jar -Dspring.location.config=application.properties /app/builds.jar > /dev/null &
        - ps aux | grep $SERVICE_NAME        
        - echo "deploy Success.."
        - echo "clean up package after deploy..."
        - sudo ls -ltr $DIR_RELEASE/agregate_service/
        - sudo rm -rf $DIR_RELEASE/agregate_service/* && sudo ls -ltr $DIR_RELEASE/agregate_service/
        - echo "processing clean up success..."

    only:
        - master        

    retry:
      max: 2
      when: always      

    allow_failure: true
    when: delayed
    start_in: 1 minutes
    after_script:
        - echo "Deploy development complete..."