variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
    - build
    - test  
    - archive
    - deploy     

build:
    stage: build
    environment:
        name: development
        url: http://188.166.214.118:9090
    tags:
        - s1
    artifacts: 
      public: true
      when: on_success     
      paths:
        - build/libs/*.jar
    before_script:   
        - pwd && cd $CI_BUILDS_DIR        

    rules:
      - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH'
      - if: '$CI_COMMIT_BRANCH == "master"'
        when: on_success          
        allow_failure: true
      - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^src/ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
        when: always
      - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^src/'
        when: manual
        allow_failure: true
      - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME'      
      - if: '$CI_COMMIT_TAG != ""'       

    script: 
        - pwd && cd $CI_BUILDS_DIR   
        # - "curl -X POST -F token=94d3a5894201ff60c047c296cad592 -F ref=master https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/trigger/pipeline"  
        - ./gradlew clean build # build package java
        - ./gradlew copy # running copy task configuration    

    retry:
      max: 2
      when: always
    allow_failure: true        
    after_script:                 
        - echo "Build development complete"    


    



    


