version: '3.1'
services:
  app:
    container_name: springboot-postgresql
    image: springbootpostgresql:1.5
    build: ./
    environment:
      - DB_SERVER=postgresqldb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "8080:8080"
    links:
      - postgresqldb
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data